# Generated by Django 5.0.6 on 2026-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_category',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Mechanic', 'Mechanic'), ('Cleaning', 'Cleaning'), ('IT Services', 'IT Services'), ('Tile', 'Tile'), ('Mason/Mistri', 'Mason/Mistri'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
